[package]
name = "deb-installer"
version = "0.1.5"
edition = "2024"

[dependencies]
anyhow = { version = "1", features = ["backtrace"] }
slint = { version = "1.10", features = ["gettext"] }
oma-pm = "0.45.0"
reqwest = "0.12"
apt-auth-config = "0.2.0"
tracing = "0.1"
zbus = { version = "5",  features = ["tokio"] }
tokio = { version = "1.41", features = ["rt", "rt-multi-thread", "macros"] }
clap = { version = "4", features = ["derive"] }
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
flume = "0.11.1"
console = "0.15"
which = "7"
human_bytes = "0.4.3"
num_enum = "0.7.3"

[features]
debug = []
