[package]
name = "deb-installer"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1", features = ["backtrace"] }
slint = "1.8.0"
oma-pm = { git = "https://github.com/AOSC-Dev/oma/", package = "oma-pm", rev = "98a5163833c1c925b419f64ceca607407c31d588"}
reqwest = "0.12"
apt-auth-config =  { git = "https://github.com/AOSC-Dev/oma/", package = "apt-auth-config", rev = "98a5163833c1c925b419f64ceca607407c31d588" }
oma-fetch = { git = "https://github.com/AOSC-Dev/oma/", package = "oma-fetch", rev = "98a5163833c1c925b419f64ceca607407c31d588"}
tracing = "0.1"
zbus = { version = "4.4",  features = ["tokio"] }
tokio = { version = "1.41", features = ["rt", "rt-multi-thread"] }
clap = { version = "4", features = ["derive"] }
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
flume = "0.11.1"
console = "0.15"
