[package]
name = "deb-installer"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1", features = ["backtrace"] }
slint = { version = "1.8.0", features = ["gettext"] }
oma-pm = "0.40"
reqwest = "0.12"
apt-auth-config =  "0.2.0"
oma-fetch = "0.17.1"
tracing = "0.1"
zbus = { version = "4.4",  features = ["tokio"] }
tokio = { version = "1.41", features = ["rt", "rt-multi-thread"] }
clap = { version = "4", features = ["derive"] }
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
flume = "0.11.1"
console = "0.15"
which = "7"
human_bytes = "0.4.3"
num_enum = "0.7.3"

[features]
debug = []
