import { GroupBox, HorizontalBox, GridBox, TabWidget, VerticalBox, Button, TextEdit, StandardButton, ProgressIndicator, Spinner, CheckBox } from "std-widgets.slint";

export component DebInstaller inherits Window {
    title: @tr("Package Installation Wizard");
    width: 500px;
    height: 260px;

    in-out property <string> package;
    in-out property <string> status;
    in-out property <string> description;
    in-out property <string> version;
    in-out property <string> installed-size;
    in-out property <string> metadata;
    in-out property <float> progress;
    in-out property <string> message;
    in-out property <bool> can-install;
    private property <bool> is-install;

    callback install();
    callback close();

    if (!is-install): VerticalLayout {
        GridBox {
            Row {
                VerticalBox {
                    vertical-stretch: 0;
                    padding-top: -10px;
                    padding-left: 15px;

                    HorizontalBox {
                        vertical-stretch: 0;
                        padding-left: 0px;
                        Text {
                            vertical-alignment: top;
                            horizontal-alignment: left;
                            font-size: 26px;
                            font-weight: 600;
                            text: root.package;
                        }
                    }
                    
                    HorizontalBox {
                        vertical-stretch: 0;
                        padding-top: -25px;
                        padding-left: 0px;
                        Text {
                            vertical-alignment: top;
                            horizontal-alignment: left;
                            text: root.version + "·" + root.installed-size + "·" + root.status;
                        }
                    }

                    HorizontalBox {
                        vertical-stretch: 0;
                        padding-top: -25px;
                        padding-left: 0px;
                        Text {
                            vertical-alignment: top;
                            horizontal-alignment: left;
                            text: root.description;
                        }
                    }
                }

                VerticalBox {
                    padding-top: -40px;
                    padding-left: -50px;
                    Image {
                        source: @image-url("/usr/share/icons/breeze/mimetypes/64/application-vnd.debian.binary-package.svg");
                        width: 128px;
                        height: 128px;
                    }
                }
            }
        }

        Rectangle {
            height: 1px;
            background: #cfcfcf;
        }

        HorizontalBox {
            vertical-stretch: 1;
            padding-left: 20px;
            Text {
                vertical-alignment: top;
                horizontal-alignment: left;
                text: @tr("This utility will help you install .deb packages. Please note that many 3rd-party software packages are not tested and verified by AOSC OS maintainers - it may not function as expected and may contain malicious content.\n\nTo install the package, press \"Install\" below and you will be prompted for administrative password; to cancel, press \"Cancel\"");
                wrap: word-wrap;
            }
        }

        HorizontalBox {
            vertical-stretch: 0;
            Button {
                text: @tr("Install");
                clicked => {
                    root.is-install = true;
                    root.install();
                }
                enabled: root.can-install;
            }

            Button {
                text: @tr("Cancel");
                clicked => {
                    root.close();
                }
            }
        }
    }

    if (root.is-install): VerticalLayout {
        HorizontalBox {
            progress-indicator := ProgressIndicator {
                min-width: 160px;
                progress: root.progress;
            }

            Text {
                vertical-alignment: center;
                horizontal-alignment: left;
                text: root.progress * 100 + "%";
            }
        }

        Rectangle {
            background: #000;
            TextInput {
                font-family: "monospace";
                color: #ffff;
                width: 100%;
                height: 100%;
                text: root.message;
                read-only: true;
                single-line: false;
            }
        }
    }
}
