import { GroupBox, HorizontalBox, GridBox, TabWidget, VerticalBox, Button, TextEdit, StandardButton, ProgressIndicator, Spinner, CheckBox } from "std-widgets.slint";

export component DebInstaller inherits Window {
    title: "DebInstaller";
    width: 500px;
    height: 480px;

    in-out property <string> package;
    in-out property <string> status;
    in-out property <string> description;
    in-out property <string> metadata;
    in-out property <float> progress;

    private property <bool> is-install;

    callback install();
    in-out property <string> message;

    if (!is-install) : GroupBox {
        width: 500px;
        height: 480px;
        GridLayout {
            GridBox {
                Row {
                    HorizontalBox {
                        Text {
                            vertical-alignment: center;
                            horizontal-alignment: left;
                            text: @tr("Package:");
                            width: 10%;
                        }

                        Text {
                            vertical-alignment: center;
                            horizontal-alignment: left;
                            text: root.package;
                            width: 20%;
                        }
                    }
                }

                Row {
                    HorizontalBox {
                        Text {
                            vertical-alignment: center;
                            horizontal-alignment: left;
                            text: @tr("Status:");
                            width: 10%;
                        }

                        Text {
                            vertical-alignment: center;
                            horizontal-alignment: left;
                            text: root.status;
                            width: 20%;
                        }
                    }
                }

                TabWidget {
                    Tab {
                        title: @tr("Description");
                        TextEdit {
                            font-size: 14px;
                            width: parent.width;
                            height: parent.height;
                            text: root.description;
                            read-only: true;
                        }
                    }

                    Tab {
                        title: @tr("Details");
                        TextEdit {
                            font-size: 14px;
                            width: parent.width;
                            height: parent.height;
                            text: root.metadata;
                            read-only: true;
                        }
                    }
                }

                Row {
                    HorizontalBox {
                        Button {
                            text: @tr("Install");
                            clicked => {
                                root.is-install = true;
                                root.install();
                            }
                        }

                        StandardButton {
                            kind: cancel;
                        }
                    }
                }
            }
        }
    }

    if (root.is-install): GridBox {
        width: 100%;
        height: 100%;
        spacing: 16px;

        Row {
            progress-indicator := ProgressIndicator {
                row: 0;
                col: 0;
                min-width: 160px;
                progress: root.progress;
            }
        }

        Row {
            Rectangle {
                TextEdit {
                    width: 100%;
                    height: 100%;
                    text: root.message;
                    read-only: true;
                }
            }
        }
    }
}
