import { GroupBox, HorizontalBox, GridBox, TabWidget, VerticalBox, Button, TextEdit, StandardButton, ProgressIndicator, Spinner, CheckBox } from "std-widgets.slint";

export component DebInstaller inherits Window {
    title: "DebInstaller";
    width: 500px;
    height: 480px;

    in-out property <string> package;
    in-out property <string> status;
    in-out property <string> description;
    in-out property <string> metadata;
    in-out property <float> progress;
    in-out property <string> message;
    in-out property <bool> can-install;
    private property <bool> is-install;

    callback install();
    callback close();

    if (!is-install): GroupBox {
        width: 100%;
        height: 100%;
        VerticalLayout {
            HorizontalBox {
                Text {
                    vertical-alignment: center;
                    horizontal-alignment: left;
                    text: @tr("Package:");
                    width: 10%;
                }

                Text {
                    vertical-alignment: center;
                    horizontal-alignment: left;
                    text: root.package;
                    width: 10%;
                }
            }

            HorizontalBox {
                Text {
                    vertical-alignment: center;
                    horizontal-alignment: left;
                    text: @tr("Status:");
                    width: 10%;
                }

                Text {
                    vertical-alignment: center;
                    horizontal-alignment: left;
                    text: root.status;
                    width: 10%;
                }
            }

            TabWidget {
                Tab {
                    title: @tr("Description");
                    Rectangle {
                        background: #ffff;
                        TextInput {
                            // color: #0000;
                            font-size: 14px;
                            width: 100%;
                            height: 100%;
                            wrap: word-wrap;
                            text: root.description;
                            read-only: true;
                            single-line: false;
                        }
                    }
                }

                Tab {
                    title: @tr("Details");
                    Rectangle {
                        background: #ffff;
                        TextInput {
                            // color: #0000;
                            font-size: 14px;
                            width: 100%;
                            height: 100%;
                            wrap: word-wrap;
                            text: root.metadata;
                            read-only: true;
                            single-line: false;
                        }
                    }
                }
            }

            HorizontalBox {
                Button {
                    text: @tr("Install");
                    clicked => {
                        root.is-install = true;
                        root.install();
                    }
                    enabled: root.can-install;
                }

                Button {
                    text: @tr("Cancel");
                    clicked => {
                        root.close();
                    }
                }
            }
        }
    }

    if (root.is-install): GroupBox {
        width: 100%;
        height: 100%;

        VerticalLayout {
            HorizontalBox {
                progress-indicator := ProgressIndicator {
                    min-width: 160px;
                    progress: root.progress;
                }
    
                Text {
                    vertical-alignment: center;
                    horizontal-alignment: left;
                    text: root.progress * 100 + "%";
                }
            }

            Rectangle {
                background: #000;
                TextInput {
                    font-family: "monospace";
                    color: #ffff;
                    width: 100%;
                    height: 100%;
                    text: root.message;
                    read-only: true;
                    single-line: false;
                }
            }
        }
    }
}
